name: connect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.11.0
  provider: ^6.1.5+1
  timezone: ^0.10.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  spotify: ^0.13.7
  marquee: ^2.3.0
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21